import sys, os
from setup import config

# make it possible to find the data python module in parent folder
sys.path.insert(0, '..') 

# final datasets text-only
PROJECT_PATH = config.PROJECT_PATH
OS_PATH_DATASET_TEXTS_ONLY = PROJECT_PATH + config.OS_PATH_DATASET_TEXTS_ONLY
OS_PATH_DATASET_TEXTS_ONLY_TEST_SPECIAL = PROJECT_PATH + config.OS_PATH_DATASET_TEXTS_ONLY_TEST_SPECIAL

# train + eval
FILENAME_HW_DATASET_TEXTS_TRAIN_EVAL = config.FILENAME_HW_DATASET_TEXTS_TRAIN_EVAL
FILENAME_MG_DATASET_TEXTS_TRAIN_EVAL_LLAMA = config.FILENAME_MG_DATASET_TEXTS_TRAIN_EVAL_LLAMA
FILENAME_MG_DATASET_TEXTS_TRAIN_EVAL_MIXED = config.FILENAME_MG_DATASET_TEXTS_TRAIN_EVAL_MIXED

# test
FILENAME_HW_DATASET_TEXTS_TEST = config.FILENAME_HW_DATASET_TEXTS_TEST
FILENAME_MG_DATASET_TEXTS_TEST_LLAMA = config.FILENAME_MG_DATASET_TEXTS_TEST_LLAMA
FILENAME_MG_DATASET_TEXTS_TEST_MIXED = config.FILENAME_MG_DATASET_TEXTS_TEST_MIXED

# special tests
FILENAME_MG_DATASET_TEXTS_TEST_SPECIAL_GPT = config.FILENAME_MG_DATASET_TEXTS_TEST_SPECIAL_GPT
FILENAME_MG_DATASET_TEXTS_TEST_SPECIAL_MISTRAL = config.FILENAME_MG_DATASET_TEXTS_TEST_SPECIAL_MISTRAL