import sys

# make it possible to find the data python module in parent folder
sys.path.insert(0, '..') 

import setup.config as config

# machine-generated llama
DATA_PATH = config.DATA_PATH
FILENAME_MACHINE_GENERATED_LLAMA_SPRINGERNATURE = config.FILENAME_MACHINE_GENERATED_LLAMA_SPRINGERNATURE
FILENAME_MACHINE_GENERATED_LLAMA_TAZ = config.FILENAME_MACHINE_GENERATED_LLAMA_TAZ
FILENAME_MACHINE_GENERATED_LLAMA_WIKIMEDIA = config.FILENAME_MACHINE_GENERATED_LLAMA_WIKIMEDIA
FILENAME_MACHINE_GENERATED_LLAMA_WIKIPEDIA = config.FILENAME_MACHINE_GENERATED_LLAMA_WIKIPEDIA
FILENAME_MACHINE_GENERATED_LLAMA_ZEITONLINE = config.FILENAME_MACHINE_GENERATED_LLAMA_ZEITONLINE
OS_PATH_MACHINE_GENERATED_TRAININGDATA_LLAMA = DATA_PATH+config.OS_PATH_MACHINE_GENERATED_TRAININGDATA_LLAMA

# machine-generated wizard
OS_PATH_MG_DATA_WIZARD_GPT_TEST_ONLY = config.PROJECT_PATH + config.OS_PATH_MG_DATA_TEST_MISTRAL_GPT
OS_PATH_MG_DATA_WIZARD_SNOOZY_MISTRAL_GPT = config.PROJECT_PATH + config.OS_PATH_MG_DATA_WIZARD_SNOOZY_MISTRAL_GPT

# human-written
PROJECT_PATH = config.PROJECT_PATH
FILENAME_HUMAN_WRITTEN_CLEANED_SPRINGERNATURE = config.FILENAME_HUMAN_WRITTEN_CLEANED_SPRINGERNATURE
FILENAME_HUMAN_WRITTEN_CLEANED_TAZ = config.FILENAME_HUMAN_WRITTEN_CLEANED_TAZ
FILENAME_HUMAN_WRITTEN_CLEANED_WIKIMEDIA = config.FILENAME_HUMAN_WRITTEN_CLEANED_WIKIMEDIA
FILENAME_HUMAN_WRITTEN_CLEANED_WIKIPEDIA = config.FILENAME_HUMAN_WRITTEN_CLEANED_WIKIPEDIA
FILENAME_HUMAN_WRITTEN_CLEANED_ZEITONLINE = config.FILENAME_HUMAN_WRITTEN_CLEANED_ZEITONLINE
OS_PATH_HUMAN_WRITTEN_CLEANED = PROJECT_PATH+config.OS_PATH_HUMAN_WRITTEN_CLEANED

human_written_files = [FILENAME_HUMAN_WRITTEN_CLEANED_SPRINGERNATURE,
                       FILENAME_HUMAN_WRITTEN_CLEANED_TAZ,
                       FILENAME_HUMAN_WRITTEN_CLEANED_WIKIMEDIA,
                       FILENAME_HUMAN_WRITTEN_CLEANED_WIKIPEDIA,
                       FILENAME_HUMAN_WRITTEN_CLEANED_ZEITONLINE]

machine_generated_files = [FILENAME_MACHINE_GENERATED_LLAMA_SPRINGERNATURE,
                           FILENAME_MACHINE_GENERATED_LLAMA_TAZ,
                           FILENAME_MACHINE_GENERATED_LLAMA_WIKIMEDIA,
                           FILENAME_MACHINE_GENERATED_LLAMA_WIKIPEDIA,
                           FILENAME_MACHINE_GENERATED_LLAMA_ZEITONLINE]


wizard_files = [
    config.FILENAME_MG_DATA_WIZARD_SPRINGERNATURE,
    config.FILENAME_MG_DATA_WIZARD_TAZ,
    config.FILENAME_MG_DATA_WIZARD_WIKIPEDIA,
    config.FILENAME_MG_DATA_WIZARD_ZEITONLINE
]
snoozy_files = [
    config.FILENAME_MG_DATA_SNOOZY_SPRINGERNATURE,
    config.FILENAME_MG_DATA_SNOOZY_TAZ,
    config.FILENAME_MG_DATA_SNOOZY_WIKIPEDIA,
    config.FILENAME_MG_DATA_SNOOZY_ZEITONLINE
] 
gpt_files = [
    config.FILENAME_MG_DATA_GPT_SPRINGERNATURE,
    config.FILENAME_MG_DATA_GPT_TAZ,
    config.FILENAME_MG_DATA_GPT_WIKIPEDIA,
    config.FILENAME_MG_DATA_GPT_ZEITONLINE
]

gpt_file_test_only = [ config.FILENAME_MG_DATA_GPT_WIKIMEDIA ]

mistral_file = [ config.FILENAME_MG_DATA_MISTRAL_TAZ ]
mistral_file_test_only = [ config.FILENAME_MG_DATA_MISTRAL_WIKIPEDIA ]

# OUTPUT
FILENAME_TOKENLENGTH_DICT_HW = config.FILENAME_TOKENLENGTH_DICT_HW
FILENAME_TOKENLENGTH_DICT_MG_LLAMA = config.FILENAME_TOKENLENGTH_DICT_MG_LLAMA
FILENAME_TOKENLENGTH_DICT_MG_MIXED = config.FILENAME_TOKENLENGTH_DICT_MG_MIXED
FILENAME_TOKENLENGTH_DICT_MG_TEST_ONLY = config.FILENAME_TOKENLENGTH_DICT_MG_TEST_ONLY

OS_PATH_STATISTICS_OUTPUT = PROJECT_PATH+config.OS_PATH_STATISTICS_OUTPUT
